name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Updated version

      - name: Login to DockerHub
        uses: docker/login-action@v3  # Updated version
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image 1
        uses: docker/build-push-action@v5  # Updated version
        with:
          context: ./SImple_Docker_Image
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/proj1-image1:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker image 2
        uses: docker/build-push-action@v5  # Updated version
        with:
          context: ./node-postres-docker
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/proj1-image2:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
