name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image 1
        uses: docker/build-push-action@v2
        with:
          context: ./Simple_Docker_Image
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/proj1-image1:latest

      - name: Build and push Docker image 2
        uses: docker/build-push-action@v2
        with:
          context: ./node-postres-docker
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/proj1-image2:latest
